/*
 * Contenido curricular, organizado por curso (idioma a aprender). Cada lección declara
 * su nivel CEFR y descriptor. Input comprensible: el diálogo usa ~90%+ vocabulario
 * cognado/reconocible; el glosario marca solo lo nuevo, en contexto (principio Krashen i+1).
 *
 * `glossary[].target` (antes `it`) es siempre el texto en el idioma que se está
 * aprendiendo — el nombre del campo es genérico a propósito porque ahora hay más de
 * un curso (antes solo existía italiano, de ahí que muchos ids/variables digan "it").
 */

const COURSES = {
  it: {
    code: 'it',
    name: 'Italiano',
    flag: '🇮🇹',
    speechLang: 'it-IT',
    lessons: [
    {
      id: 'a1_u1_saluti',
      cefr: 'A1',
      descriptor: 'Puede presentarse y preguntar/responder datos personales básicos.',
      title: 'Saluti e presentazioni',
      titleEs: 'Saludos y presentaciones',
      dialogue: [
        { speaker: 'Marco', line: 'Ciao! Come ti chiami?' },
        { speaker: 'Giulia', line: 'Mi chiamo Giulia. E tu?' },
        { speaker: 'Marco', line: 'Io sono Marco. Piacere!' },
        { speaker: 'Giulia', line: 'Piacere mio!' },
      ],
      // Guía fonética simple (no IPA): mayúsculas = sílaba tónica, lectura pensada
      // para hispanohablantes. Claves siempre en minúscula (lookup case-insensitive).
      phonetics: {
        'ciao! come ti chiami?': 'CHAO! KO-me ti KIA-mi?',
        'mi chiamo giulia. e tu?': 'mi KIA-mo YU-lia. e tu?',
        'io sono marco. piacere!': 'IO SO-no MAR-ko. pia-CHE-re!',
        'piacere mio!': 'pia-CHE-re MI-o!',
        'come ti chiami?': 'KO-me ti KIA-mi?',
        'mi chiamo...': 'mi KIA-mo...',
        'piacere': 'pia-CHE-re',
        'sono': 'SO-no', 'sei': 'SEI', 'è': 'E', 'siamo': 'SIA-mo', 'siete': 'SIE-te',
      },
      glossary: [
        { target: 'Come ti chiami?', es: '¿Cómo te llamas?', note: 'Literal: "¿cómo te llamas a ti mismo?" — verbo reflexivo chiamarsi.' },
        { target: 'Mi chiamo...', es: 'Me llamo...', note: null },
        { target: 'Piacere', es: 'Mucho gusto', note: 'Se usa igual que en español al presentarse; no hace falta traducir literal.' },
      ],
      grammar: {
        title: 'El verbo "essere" (ser/estar) — presente',
        explanation: 'Essere es irregular y altísima frecuencia: aparece en casi toda frase de presentación. A diferencia del español, italiano no distingue ser/estar con dos verbos — essere cubre ambos usos centrales.',
        table: [
          ['io', 'sono'], ['tu', 'sei'], ['lui/lei', 'è'],
          ['noi', 'siamo'], ['voi', 'siete'], ['loro', 'sono'],
        ],
      },
      exercises: [
        {
          id: 'ex1', type: 'fill',
          prompt: 'Completa: Io ___ Marco.',
          answer: 'sono',
          explanation: '"io" siempre va con "sono" (1ª persona singular de essere).',
          srsFront: 'Io ___ Marco. (essere, io)', srsBack: 'sono',
        },
        {
          id: 'ex2', type: 'fill',
          prompt: 'Completa: Tu ___ Giulia?',
          answer: 'sei',
          explanation: '"tu" siempre va con "sei".',
          srsFront: 'Tu ___ Giulia? (essere, tu)', srsBack: 'sei',
        },
        {
          id: 'ex3', type: 'fill',
          prompt: 'Completa: Noi ___ studenti.',
          answer: 'siamo',
          explanation: '"noi" va con "siamo".',
          srsFront: 'Noi ___ studenti. (essere, noi)', srsBack: 'siamo',
        },
        {
          id: 'ex4', type: 'translate',
          prompt: 'Traduce al italiano: "Mucho gusto"',
          answer: 'piacere',
          explanation: '"Piacere" se usa solo, como en español.',
          srsFront: '¿Cómo se dice "Mucho gusto" en italiano?', srsBack: 'Piacere',
          reverseFront: 'Piacere', reverseBack: 'Mucho gusto',
        },
        {
          id: 'ex5', type: 'translate',
          prompt: 'Traduce al italiano: "¿Cómo te llamas?"',
          answer: 'come ti chiami',
          explanation: '"Come ti chiami?" — chiamarsi es reflexivo (como en español "llamarse").',
          srsFront: '¿Cómo se dice "¿Cómo te llamas?" en italiano?', srsBack: 'Come ti chiami?',
          reverseFront: 'Come ti chiami?', reverseBack: '¿Cómo te llamas?',
        },
      ],
    },
    {
      id: 'a1_u2_famiglia',
      cefr: 'A1',
      descriptor: 'Puede hablar de su familia usando "avere" y vocabulario básico de parentesco.',
      title: 'La famiglia',
      titleEs: 'La familia',
      dialogue: [
        { speaker: 'Marco', line: 'Hai fratelli?' },
        { speaker: 'Giulia', line: 'Sì, ho un fratello e una sorella. E tu?' },
        { speaker: 'Marco', line: 'Io ho solo una sorella. Come si chiama tua sorella?' },
        { speaker: 'Giulia', line: 'Si chiama Sofia.' },
      ],
      phonetics: {
        'hai fratelli?': 'AI fra-TEL-li?',
        'sì, ho un fratello e una sorella. e tu?': 'si, o un fra-TEL-lo e U-na so-REL-la. e tu?',
        'io ho solo una sorella. come si chiama tua sorella?': 'IO o SO-lo U-na so-REL-la. KO-me si KIA-ma TU-a so-REL-la?',
        'si chiama sofia.': 'si KIA-ma so-FI-a.',
        'tua sorella': 'TU-a so-REL-la',
        'come si chiama...?': 'KO-me si KIA-ma...?',
        'ho': 'O', 'hai': 'AI', 'ha': 'A', 'abbiamo': 'ab-BIA-mo', 'avete': 'a-VE-te', 'hanno': 'AN-no',
        'fratello': 'fra-TEL-lo',
      },
      glossary: [
        { target: 'Hai fratelli?', es: '¿Tienes hermanos?', note: 'Avere = tener (no confundir con essere, ya visto en la Unidad 1).' },
        { target: 'tua sorella', es: 'tu hermana', note: 'Posesivo antes del sustantivo, como en español.' },
        { target: 'Come si chiama...?', es: '¿Cómo se llama...?', note: 'Mismo verbo chiamarsi de la Unidad 1, ahora en 3ª persona (si chiama, no ti chiami).' },
      ],
      grammar: {
        title: 'El verbo "avere" (tener) — presente',
        explanation: 'Avere es irregular y de altísima frecuencia, como essere (Unidad 1) — pero no hay que confundirlos: essere = ser/estar, avere = tener. En italiano, a diferencia del español, la "h" de "ho/hai/ha/hanno" no suena pero se escribe siempre (marca ortográfica, no fonética).',
        table: [
          ['io', 'ho'], ['tu', 'hai'], ['lui/lei', 'ha'],
          ['noi', 'abbiamo'], ['voi', 'avete'], ['loro', 'hanno'],
        ],
      },
      exercises: [
        {
          id: 'ex1', type: 'fill',
          prompt: 'Completa: Io ___ un fratello.',
          answer: 'ho',
          explanation: '"io" va con "ho" (avere), no con "sono" (essere) — son verbos distintos.',
          srsFront: 'Io ___ un fratello. (avere, io)', srsBack: 'ho',
        },
        {
          id: 'ex2', type: 'fill',
          prompt: 'Completa: Tu ___ una sorella?',
          answer: 'hai',
          explanation: '"tu" va con "hai".',
          srsFront: 'Tu ___ una sorella? (avere, tu)', srsBack: 'hai',
        },
        {
          id: 'ex3', type: 'fill',
          prompt: 'Completa: Noi ___ una famiglia grande.',
          answer: 'abbiamo',
          explanation: '"noi" va con "abbiamo".',
          srsFront: 'Noi ___ una famiglia grande. (avere, noi)', srsBack: 'abbiamo',
        },
        {
          id: 'ex4', type: 'translate',
          prompt: 'Traduce al italiano: "hermano"',
          answer: 'fratello',
          explanation: '"Fratello" — cognado reconocible del latín frater.',
          srsFront: '¿Cómo se dice "hermano" en italiano?', srsBack: 'Fratello',
          reverseFront: 'Fratello', reverseBack: 'Hermano',
        },
        {
          id: 'ex5', type: 'translate',
          prompt: 'Traduce al italiano: "¿Tienes hermanos?"',
          answer: 'hai fratelli',
          explanation: '"Hai fratelli?" — avere (no essere) para expresar posesión/parentesco.',
          srsFront: '¿Cómo se dice "¿Tienes hermanos?" en italiano?', srsBack: 'Hai fratelli?',
          reverseFront: 'Hai fratelli?', reverseBack: '¿Tienes hermanos?',
        },
      ],
    },
    {
      id: 'a1_u3_eta',
      cefr: 'A1',
      descriptor: 'Puede decir y preguntar la edad, y usar los números del 0 al 10.',
      title: "L'età e i numeri",
      titleEs: 'La edad y los números',
      dialogue: [
        { speaker: 'Marco', line: 'Quanti anni hai?' },
        { speaker: 'Giulia', line: 'Ho venti anni. E tu?' },
        { speaker: 'Marco', line: 'Io ho ventidue anni.' },
        { speaker: 'Giulia', line: 'Sei giovane!' },
      ],
      phonetics: {
        'quanti anni hai?': 'KUAN-ti AN-ni ai?',
        'ho venti anni. e tu?': 'O VEN-ti AN-ni. e tu?',
        'io ho ventidue anni.': 'IO o ven-ti-DU-e AN-ni.',
        'sei giovane!': 'SEI YO-va-ne!',
        'giovane': 'YO-va-ne',
        'zero': 'TSE-ro', 'uno': 'U-no', 'due': 'DU-e', 'tre': 'TRE', 'quattro': 'KUAT-tro',
        'cinque': 'CHIN-kue', 'sei': 'SEI', 'sette': 'SET-te', 'otto': 'OT-to', 'nove': 'NO-ve', 'dieci': 'DIE-chi',
      },
      glossary: [
        { target: 'Quanti anni hai?', es: '¿Cuántos años tienes?', note: 'Literal "¿Cuántos años tienes?" — igual estructura que el español.' },
        { target: 'giovane', es: 'joven', note: null },
      ],
      grammar: {
        title: '"Avere ... anni" para la edad, y los números 0-10',
        explanation: 'Igual que en español decimos "tener X años" (no "ser X años"), en italiano se usa avere + número + anni — mismo patrón, transferencia directa desde el español (ya conocés avere de la Unidad 2). A diferencia del español, "anni" siempre va en plural, incluso con "un anno" pasa a plural desde "due anni" en adelante, igual que en español.',
        table: [
          ['0', 'zero'], ['1', 'uno'], ['2', 'due'], ['3', 'tre'], ['4', 'quattro'],
          ['5', 'cinque'], ['6', 'sei'], ['7', 'sette'], ['8', 'otto'], ['9', 'nove'], ['10', 'dieci'],
        ],
      },
      exercises: [
        {
          id: 'ex1', type: 'fill',
          prompt: 'Completa: Io ___ venti anni.',
          answer: 'ho',
          explanation: 'Repaso de avere (Unidad 2): "io" siempre va con "ho", también para la edad.',
          srsFront: 'Io ___ venti anni. (avere, io)', srsBack: 'ho',
        },
        {
          id: 'ex2', type: 'fill',
          prompt: 'Completa: Tu ___ dieci anni?',
          answer: 'hai',
          explanation: '"tu" va con "hai".',
          srsFront: 'Tu ___ dieci anni? (avere, tu)', srsBack: 'hai',
        },
        {
          id: 'ex3', type: 'translate',
          prompt: 'Traduce al italiano: "¿Cuántos años tienes?"',
          answer: 'quanti anni hai',
          explanation: '"Quanti anni hai?" — misma estructura que en español.',
          srsFront: '¿Cómo se dice "¿Cuántos años tienes?" en italiano?', srsBack: 'Quanti anni hai?',
          reverseFront: 'Quanti anni hai?', reverseBack: '¿Cuántos años tienes?',
        },
        {
          id: 'ex4', type: 'translate',
          prompt: 'Traduce al italiano: "diez"',
          answer: 'dieci',
          explanation: '"Dieci" — cognado reconocible del latín decem.',
          srsFront: '¿Cómo se dice "diez" en italiano?', srsBack: 'Dieci',
          reverseFront: 'Dieci', reverseBack: 'Diez',
        },
        {
          id: 'ex5', type: 'translate',
          prompt: 'Traduce al italiano: "cinco"',
          answer: 'cinque',
          explanation: '"Cinque" — cognado reconocible del latín quinque.',
          srsFront: '¿Cómo se dice "cinco" en italiano?', srsBack: 'Cinque',
          reverseFront: 'Cinque', reverseBack: 'Cinco',
        },
      ],
    },
    {
      id: 'a1_u4_parlare',
      cefr: 'A1',
      descriptor: 'Puede decir qué idiomas habla usando el patrón regular de los verbos en -are.',
      title: 'Che lingue parli?',
      titleEs: '¿Qué idiomas hablas?',
      dialogue: [
        { speaker: 'Marco', line: 'Parli italiano?' },
        { speaker: 'Giulia', line: 'Sì, parlo italiano e spagnolo. Tu parli inglese?' },
        { speaker: 'Marco', line: "Sì, parlo inglese e un po' d'italiano." },
        { speaker: 'Giulia', line: 'Bravo!' },
      ],
      phonetics: {
        'parli italiano?': 'PAR-li i-ta-LIA-no?',
        'sì, parlo italiano e spagnolo. tu parli inglese?': 'si, PAR-lo i-ta-LIA-no e spa-ÑO-lo. tu PAR-li in-GLE-se?',
        "sì, parlo inglese e un po' d'italiano.": 'si, PAR-lo in-GLE-se e un PO di-ta-LIA-no.',
        'bravo!': 'BRA-vo!',
        "un po' di": 'un PO di',
        'parlo': 'PAR-lo', 'parli': 'PAR-li', 'parla': 'PAR-la',
        'parliamo': 'par-LIA-mo', 'parlate': 'par-LA-te', 'parlano': 'PAR-la-no',
        'parlare': 'par-LA-re',
      },
      glossary: [
        { target: "un po' di", es: 'un poco de', note: null },
        { target: 'Bravo!', es: '¡Bien hecho!', note: 'Cognado directo — mismo uso que en español al felicitar.' },
      ],
      grammar: {
        title: 'Verbos regulares en -are (ej. "parlare" = hablar)',
        explanation: 'A diferencia de essere y avere (irregulares, Unidades 1 y 2 — hay que memorizar cada forma), "parlare" sigue un patrón regular que se repite en cientos de verbos italianos (mangiare=comer, guardare=mirar, ascoltare=escuchar...). Aprender esta terminación una sola vez multiplica el vocabulario que ya podés conjugar.',
        table: [
          ['io', 'parlo'], ['tu', 'parli'], ['lui/lei', 'parla'],
          ['noi', 'parliamo'], ['voi', 'parlate'], ['loro', 'parlano'],
        ],
      },
      exercises: [
        {
          id: 'ex1', type: 'fill',
          prompt: 'Completa: Io ___ italiano.',
          answer: 'parlo',
          explanation: '"io" + verbos en -are → termina en "-o" (parlo).',
          srsFront: 'Io ___ italiano. (parlare, io)', srsBack: 'parlo',
        },
        {
          id: 'ex2', type: 'fill',
          prompt: 'Completa: Tu ___ inglese?',
          answer: 'parli',
          explanation: '"tu" + verbos en -are → termina en "-i" (parli).',
          srsFront: 'Tu ___ inglese? (parlare, tu)', srsBack: 'parli',
        },
        {
          id: 'ex3', type: 'fill',
          prompt: 'Completa: Noi ___ spagnolo.',
          answer: 'parliamo',
          explanation: '"noi" + verbos en -are → termina en "-iamo" (parliamo).',
          srsFront: 'Noi ___ spagnolo. (parlare, noi)', srsBack: 'parliamo',
        },
        {
          id: 'ex4', type: 'translate',
          prompt: 'Traduce al italiano: "hablar" (infinitivo)',
          answer: 'parlare',
          explanation: '"Parlare" — cognado reconocible; el patrón -are es el más común entre los verbos italianos.',
          srsFront: '¿Cómo se dice "hablar" en italiano?', srsBack: 'Parlare',
          reverseFront: 'Parlare', reverseBack: 'Hablar',
        },
        {
          id: 'ex5', type: 'translate',
          prompt: 'Traduce al italiano: "¿Hablas italiano?"',
          answer: 'parli italiano',
          explanation: '"Parli italiano?" — "tu" siempre con "parli".',
          srsFront: '¿Cómo se dice "¿Hablas italiano?" en italiano?', srsBack: 'Parli italiano?',
          reverseFront: 'Parli italiano?', reverseBack: '¿Hablas italiano?',
        },
      ],
    },
    {
      id: 'a1_u5_prendere',
      cefr: 'A1',
      descriptor: 'Puede pedir algo en un bar/café usando el segundo patrón de conjugación regular (-ere).',
      title: 'Cosa prendi?',
      titleEs: '¿Qué tomas?',
      dialogue: [
        { speaker: 'Marco', line: 'Cosa prendi?' },
        { speaker: 'Giulia', line: 'Prendo un caffè. E tu?' },
        { speaker: 'Marco', line: 'Io prendo un tè.' },
        { speaker: 'Giulia', line: 'Va bene!' },
      ],
      phonetics: {
        'cosa prendi?': 'KO-sa PREN-di?',
        'prendo un caffè. e tu?': 'PREN-do un kaf-FE. e tu?',
        'io prendo un tè.': 'IO PREN-do un TE.',
        'va bene!': 'va BE-ne!', 'va bene': 'va BE-ne',
        'prendo': 'PREN-do', 'prendi': 'PREN-di', 'prende': 'PREN-de',
        'prendiamo': 'pren-DIA-mo', 'prendete': 'pren-DE-te', 'prendono': 'PREN-do-no',
        'prendere': 'pren-DE-re',
      },
      glossary: [
        { target: 'Cosa prendi?', es: '¿Qué tomas/pedís?', note: 'Se usa así en bares y cafés, no solo literal "tomar".' },
        { target: 'Va bene', es: 'Está bien / dale', note: null },
      ],
      grammar: {
        title: 'Verbos regulares en -ere (ej. "prendere" = tomar/pedir)',
        explanation: 'Segundo patrón regular, después de -are (Unidad 4, "parlare"). Comparten "io" (-o) y "tu" (-i), pero difieren en el resto: lui/lei termina en "-e" (no "-a"), voi en "-ete" (no "-ate"), loro en "-ono" (no "-ano"). Reconocer estas dos terminaciones (-are, -ere) ya cubre la mayoría de verbos regulares italianos.',
        table: [
          ['io', 'prendo'], ['tu', 'prendi'], ['lui/lei', 'prende'],
          ['noi', 'prendiamo'], ['voi', 'prendete'], ['loro', 'prendono'],
        ],
      },
      exercises: [
        {
          id: 'ex1', type: 'fill',
          prompt: 'Completa: Io ___ un caffè.',
          answer: 'prendo',
          explanation: '"io" + verbos en -ere → también termina en "-o" (igual que en -are).',
          srsFront: 'Io ___ un caffè. (prendere, io)', srsBack: 'prendo',
        },
        {
          id: 'ex2', type: 'fill',
          prompt: 'Completa: Tu ___ un tè?',
          answer: 'prendi',
          explanation: '"tu" + verbos en -ere → también termina en "-i" (igual que en -are).',
          srsFront: 'Tu ___ un tè? (prendere, tu)', srsBack: 'prendi',
        },
        {
          id: 'ex3', type: 'fill',
          prompt: 'Completa: Lei ___ un cappuccino.',
          answer: 'prende',
          explanation: '"lui/lei" + verbos en -ere → termina en "-e" (a diferencia de "-a" en -are).',
          srsFront: 'Lei ___ un cappuccino. (prendere, lei)', srsBack: 'prende',
        },
        {
          id: 'ex4', type: 'translate',
          prompt: 'Traduce al italiano: "tomar/pedir" (infinitivo)',
          answer: 'prendere',
          explanation: '"Prendere" — el segundo patrón regular más común, después de -are.',
          srsFront: '¿Cómo se dice "tomar/pedir" en italiano?', srsBack: 'Prendere',
          reverseFront: 'Prendere', reverseBack: 'Tomar/pedir',
        },
        {
          id: 'ex5', type: 'translate',
          prompt: 'Traduce al italiano: "¿Qué tomas?"',
          answer: 'cosa prendi',
          explanation: '"Cosa prendi?" — expresión fija para pedir en un bar/café.',
          srsFront: '¿Cómo se dice "¿Qué tomas?" en italiano?', srsBack: 'Cosa prendi?',
          reverseFront: 'Cosa prendi?', reverseBack: '¿Qué tomas?',
        },
      ],
    },
    {
      id: 'a1_u6_dormire',
      cefr: 'A1',
      descriptor: 'Puede hablar de hábitos simples usando el tercer patrón de conjugación regular (-ire).',
      title: 'Dormi bene?',
      titleEs: '¿Duermes bien?',
      dialogue: [
        { speaker: 'Marco', line: 'Dormi bene stanotte?' },
        { speaker: 'Giulia', line: 'Sì, dormo bene. Tu dormi bene?' },
        { speaker: 'Marco', line: 'No, non dormo bene stanotte.' },
        { speaker: 'Giulia', line: 'Peccato!' },
      ],
      phonetics: {
        'dormi bene stanotte?': 'DOR-mi BE-ne sta-NOT-te?',
        'sì, dormo bene. tu dormi bene?': 'si, DOR-mo BE-ne. tu DOR-mi BE-ne?',
        'no, non dormo bene stanotte.': 'no, non DOR-mo BE-ne sta-NOT-te.',
        'peccato!': 'pek-KA-to!',
        'stanotte': 'sta-NOT-te', 'non dormo': 'non DOR-mo',
        'dormo': 'DOR-mo', 'dormi': 'DOR-mi', 'dorme': 'DOR-me',
        'dormiamo': 'dor-MIA-mo', 'dormite': 'dor-MI-te', 'dormono': 'DOR-mo-no',
        'dormire': 'dor-MI-re',
      },
      glossary: [
        { target: 'stanotte', es: 'esta noche', note: null },
        { target: 'non dormo', es: 'no duermo', note: '"non" antes del verbo niega la oración, como el "no" del español antes del verbo.' },
        { target: 'Peccato!', es: '¡Qué lástima!', note: null },
      ],
      grammar: {
        title: 'Verbos regulares en -ire (ej. "dormire" = dormir)',
        explanation: 'Tercer y último patrón regular, después de -are (parlare) y -ere (prendere). La buena noticia: -ire comparte casi todas las terminaciones con -ere (io/tu/lui-lei/noi/loro son iguales) — la única diferencia es "voi": "-ete" en -ere (prendete) vs "-ite" en -ire (dormite). Con estos 3 patrones ya podés conjugar la mayoría de verbos regulares del italiano.',
        table: [
          ['io', 'dormo'], ['tu', 'dormi'], ['lui/lei', 'dorme'],
          ['noi', 'dormiamo'], ['voi', 'dormite'], ['loro', 'dormono'],
        ],
      },
      exercises: [
        {
          id: 'ex1', type: 'fill',
          prompt: 'Completa: Io ___ bene.',
          answer: 'dormo',
          explanation: '"io" + verbos en -ire → termina en "-o" (igual que -are y -ere).',
          srsFront: 'Io ___ bene. (dormire, io)', srsBack: 'dormo',
        },
        {
          id: 'ex2', type: 'fill',
          prompt: 'Completa: Tu ___ bene stanotte?',
          answer: 'dormi',
          explanation: '"tu" + verbos en -ire → termina en "-i" (igual que -are y -ere).',
          srsFront: 'Tu ___ bene stanotte? (dormire, tu)', srsBack: 'dormi',
        },
        {
          id: 'ex3', type: 'fill',
          prompt: 'Completa: Noi ___ bene.',
          answer: 'dormiamo',
          explanation: '"noi" + verbos en -ire → termina en "-iamo" (igual en los 3 patrones regulares).',
          srsFront: 'Noi ___ bene. (dormire, noi)', srsBack: 'dormiamo',
        },
        {
          id: 'ex4', type: 'translate',
          prompt: 'Traduce al italiano: "dormir" (infinitivo)',
          answer: 'dormire',
          explanation: '"Dormire" — tercer patrón regular, comparte casi todo con -ere salvo "voi".',
          srsFront: '¿Cómo se dice "dormir" en italiano?', srsBack: 'Dormire',
          reverseFront: 'Dormire', reverseBack: 'Dormir',
        },
        {
          id: 'ex5', type: 'translate',
          prompt: 'Traduce al italiano: "esta noche"',
          answer: 'stanotte',
          explanation: '"Stanotte" — de "questa notte" (esta noche), contraído.',
          srsFront: '¿Cómo se dice "esta noche" en italiano?', srsBack: 'Stanotte',
          reverseFront: 'Stanotte', reverseBack: 'Esta noche',
        },
      ],
    },
    ],
  },

  pt: {
    code: 'pt',
    name: 'Português',
    flag: '🇧🇷',
    speechLang: 'pt-BR',
    lessons: [
      {
        id: 'pt_a1_u1_cumprimentos',
        cefr: 'A1',
        descriptor: 'Pode se apresentar e perguntar/responder dados pessoais básicos.',
        title: 'Cumprimentos e apresentações',
        titleEs: 'Saludos y presentaciones',
        dialogue: [
          { speaker: 'João', line: 'Oi! Como você se chama?' },
          { speaker: 'Maria', line: 'Meu nome é Maria. E você?' },
          { speaker: 'João', line: 'Eu me chamo João. Prazer!' },
          { speaker: 'Maria', line: 'Prazer em te conhecer!' },
        ],
        phonetics: {
          'oi! como você se chama?': 'OI! KO-mu vo-SE si SHA-ma?',
          'meu nome é maria. e você?': 'meu NO-mi E ma-RI-a. i vo-SE?',
          'eu me chamo joão. prazer!': 'eu mi SHA-mu jo-ÃUN. pra-ZER!',
          'prazer em te conhecer!': 'pra-ZER en tchi ko-nye-SER!',
          'como você se chama?': 'KO-mu vo-SE si SHA-ma?',
          'meu nome é...': 'meu NO-mi E...',
          'prazer': 'pra-ZER',
          'sou': 'SO', 'é': 'E', 'somos': 'SO-mus', 'são': 'SÃUN',
        },
        glossary: [
          { target: 'Como você se chama?', es: '¿Cómo te llamas?', note: 'Literal "¿como você se chama a si mesmo?" — verbo reflexivo chamar-se, igual de directo que en español "llamarse".' },
          { target: 'Meu nome é...', es: 'Mi nombre es... / Me llamo...', note: null },
          { target: 'Prazer', es: 'Mucho gusto', note: 'Cognado de "placer"; se usa solo al presentarse, igual que en español.' },
        ],
        grammar: {
          title: 'El verbo "ser" — presente',
          explanation: 'A diferencia del italiano (que no distingue ser/estar), el portugués sí tiene dos verbos separados — igual que el español: "ser" (identidad, características permanentes) y "estar" (estados, ubicación). La conjugación de "ser" es prácticamente un calco del español: soy→sou, es→é, somos→somos, son→são. Transferencia directa, muy poco que memorizar de cero.',
          table: [
            ['eu', 'sou'], ['você', 'é'], ['ele/ela', 'é'],
            ['nós', 'somos'], ['vocês', 'são'], ['eles/elas', 'são'],
          ],
        },
        exercises: [
          {
            id: 'ex1', type: 'fill',
            prompt: 'Completa: Eu ___ João.',
            answer: 'sou',
            explanation: '"eu" siempre va con "sou" — igual que "yo soy" en español.',
            srsFront: 'Eu ___ João. (ser, eu)', srsBack: 'sou',
          },
          {
            id: 'ex2', type: 'fill',
            prompt: 'Completa: Você ___ Maria?',
            answer: 'é',
            explanation: '"você" va con "é" (3ª persona, aunque "você" signifique "tú" en el trato).',
            srsFront: 'Você ___ Maria? (ser, você)', srsBack: 'é',
          },
          {
            id: 'ex3', type: 'fill',
            prompt: 'Completa: Nós ___ estudantes.',
            answer: 'somos',
            explanation: '"nós" va con "somos" — idéntico al español.',
            srsFront: 'Nós ___ estudantes. (ser, nós)', srsBack: 'somos',
          },
          {
            id: 'ex4', type: 'translate',
            prompt: 'Traduce al portugués: "Mucho gusto"',
            answer: 'prazer',
            explanation: '"Prazer" se usa solo, como en español.',
            srsFront: '¿Cómo se dice "Mucho gusto" en portugués?', srsBack: 'Prazer',
            reverseFront: 'Prazer', reverseBack: 'Mucho gusto',
          },
          {
            id: 'ex5', type: 'translate',
            prompt: 'Traduce al portugués: "¿Cómo te llamas?"',
            answer: 'como você se chama',
            explanation: '"Como você se chama?" — chamar-se es reflexivo (como en español "llamarse").',
            srsFront: '¿Cómo se dice "¿Cómo te llamas?" en portugués?', srsBack: 'Como você se chama?',
            reverseFront: 'Como você se chama?', reverseBack: '¿Cómo te llamas?',
          },
        ],
      },
      {
        id: 'pt_a1_u2_familia',
        cefr: 'A1',
        descriptor: 'Pode falar da sua família usando "ter" e vocabulário básico de parentesco.',
        title: 'A família',
        titleEs: 'La familia',
        dialogue: [
          { speaker: 'João', line: 'Você tem irmãos?' },
          { speaker: 'Maria', line: 'Sim, tenho um irmão e uma irmã. E você?' },
          { speaker: 'João', line: 'Eu tenho só uma irmã. Como se chama sua irmã?' },
          { speaker: 'Maria', line: 'Ela se chama Sofia.' },
        ],
        phonetics: {
          'você tem irmãos?': 'vo-SE ten ir-MÃUNS?',
          'sim, tenho um irmão e uma irmã. e você?': 'sin, TE-nyu un ir-MÃUN i U-ma ir-MÃ. i vo-SE?',
          'eu tenho só uma irmã. como se chama sua irmã?': 'eu TE-nyu SO U-ma ir-MÃ. KO-mu si SHA-ma SU-a ir-MÃ?',
          'ela se chama sofia.': 'E-la si SHA-ma so-FI-a.',
          'sua irmã': 'SU-a ir-MÃ',
          'como se chama...?': 'KO-mu si SHA-ma...?',
          'tenho': 'TE-nyu', 'tem': 'TEN', 'temos': 'TE-mus', 'têm': 'TEIN',
          'irmão': 'ir-MÃUN',
        },
        glossary: [
          { target: 'Você tem irmãos?', es: '¿Tienes hermanos?', note: 'Ter = tener (no confundir con ser, ya visto en la Unidad 1) — igual distinción que en español.' },
          { target: 'sua irmã', es: 'tu hermana', note: 'Posesivo antes del sustantivo, como en español.' },
          { target: 'Como se chama...?', es: '¿Cómo se llama...?', note: 'Mismo verbo chamar-se de la Unidad 1, ahora en 3ª persona.' },
        ],
        grammar: {
          title: 'El verbo "ter" (tener) — presente',
          explanation: 'Ter es irregular y de altísima frecuencia, como ser (Unidad 1) — no hay que confundirlos: ser = ser/identidad, ter = tener. A diferencia del español "tener" (tengo/tienes/tiene), portugués usa tenho/tem/tem — nota que "você tem" y "ele/ela tem" comparten la misma forma "tem".',
          table: [
            ['eu', 'tenho'], ['você', 'tem'], ['ele/ela', 'tem'],
            ['nós', 'temos'], ['vocês', 'têm'], ['eles/elas', 'têm'],
          ],
        },
        exercises: [
          {
            id: 'ex1', type: 'fill',
            prompt: 'Completa: Eu ___ um irmão.',
            answer: 'tenho',
            explanation: '"eu" va con "tenho" (ter), no con "sou" (ser) — son verbos distintos.',
            srsFront: 'Eu ___ um irmão. (ter, eu)', srsBack: 'tenho',
          },
          {
            id: 'ex2', type: 'fill',
            prompt: 'Completa: Você ___ uma irmã?',
            answer: 'tem',
            explanation: '"você" va con "tem".',
            srsFront: 'Você ___ uma irmã? (ter, você)', srsBack: 'tem',
          },
          {
            id: 'ex3', type: 'fill',
            prompt: 'Completa: Nós ___ uma família grande.',
            answer: 'temos',
            explanation: '"nós" va con "temos".',
            srsFront: 'Nós ___ uma família grande. (ter, nós)', srsBack: 'temos',
          },
          {
            id: 'ex4', type: 'translate',
            prompt: 'Traduce al portugués: "hermano"',
            answer: 'irmão',
            explanation: '"Irmão" — cognado reconocible del latín germanus, mismo origen que "hermano".',
            srsFront: '¿Cómo se dice "hermano" en portugués?', srsBack: 'Irmão',
            reverseFront: 'Irmão', reverseBack: 'Hermano',
          },
          {
            id: 'ex5', type: 'translate',
            prompt: 'Traduce al portugués: "¿Tienes hermanos?"',
            answer: 'você tem irmãos',
            explanation: '"Você tem irmãos?" — ter (no ser) para expresar posesión/parentesco.',
            srsFront: '¿Cómo se dice "¿Tienes hermanos?" en portugués?', srsBack: 'Você tem irmãos?',
            reverseFront: 'Você tem irmãos?', reverseBack: '¿Tienes hermanos?',
          },
        ],
      },
      {
        id: 'pt_a1_u3_idade',
        cefr: 'A1',
        descriptor: 'Pode dizer e perguntar a idade, e usar os números de 0 a 10.',
        title: 'A idade e os números',
        titleEs: 'La edad y los números',
        dialogue: [
          { speaker: 'João', line: 'Quantos anos você tem?' },
          { speaker: 'Maria', line: 'Tenho vinte anos. E você?' },
          { speaker: 'João', line: 'Eu tenho vinte e dois anos.' },
          { speaker: 'Maria', line: 'Você é jovem!' },
        ],
        phonetics: {
          'quantos anos você tem?': 'KUAN-tus A-nus vo-SE ten?',
          'tenho vinte anos. e você?': 'TE-nyu VIN-tchi A-nus. i vo-SE?',
          'eu tenho vinte e dois anos.': 'eu TE-nyu VIN-tchi i DOIS A-nus.',
          'você é jovem!': 'vo-SE E JO-ven!',
          'jovem': 'JO-ven',
          'zero': 'ZE-ru', 'um': 'UN', 'dois': 'DOIS', 'três': 'TRES', 'quatro': 'KUA-tru',
          'cinco': 'SIN-ku', 'seis': 'SEIS', 'sete': 'SE-tchi', 'oito': 'OI-tu', 'nove': 'NO-vi', 'dez': 'DES',
        },
        glossary: [
          { target: 'Quantos anos você tem?', es: '¿Cuántos años tienes?', note: 'Ter (no ser) para la edad — mismo patrón que "tener años" en español; repaso del verbo de la Unidad 2.' },
          { target: 'jovem', es: 'joven', note: 'Cognado directo.' },
        ],
        grammar: {
          title: '"Ter ... anos" para la edad, y los números 0-10',
          explanation: 'Igual que en español decimos "tener X años" (no "ser X años"), en portugués se usa ter + número + anos — mismo patrón que en italiano (avere ... anni) y transferencia directa desde el español, ya conocés "ter" de la Unidad 2. Como en español, "um ano" es singular, pero desde "dois anos" en adelante "anos" va en plural.',
          table: [
            ['0', 'zero'], ['1', 'um'], ['2', 'dois'], ['3', 'três'], ['4', 'quatro'],
            ['5', 'cinco'], ['6', 'seis'], ['7', 'sete'], ['8', 'oito'], ['9', 'nove'], ['10', 'dez'],
          ],
        },
        exercises: [
          {
            id: 'ex1', type: 'fill',
            prompt: 'Completa: Eu ___ vinte anos.',
            answer: 'tenho',
            explanation: 'Repaso de ter (Unidad 2): "eu" siempre va con "tenho", también para la edad.',
            srsFront: 'Eu ___ vinte anos. (ter, eu)', srsBack: 'tenho',
          },
          {
            id: 'ex2', type: 'fill',
            prompt: 'Completa: Você ___ dez anos?',
            answer: 'tem',
            explanation: '"você" va con "tem".',
            srsFront: 'Você ___ dez anos? (ter, você)', srsBack: 'tem',
          },
          {
            id: 'ex3', type: 'translate',
            prompt: 'Traduce al portugués: "¿Cuántos años tienes?"',
            answer: 'quantos anos você tem',
            explanation: '"Quantos anos você tem?" — misma estructura que en español.',
            srsFront: '¿Cómo se dice "¿Cuántos años tienes?" en portugués?', srsBack: 'Quantos anos você tem?',
            reverseFront: 'Quantos anos você tem?', reverseBack: '¿Cuántos años tienes?',
          },
          {
            id: 'ex4', type: 'translate',
            prompt: 'Traduce al portugués: "diez"',
            answer: 'dez',
            explanation: '"Dez" — cognado reconocible del latín decem, igual raíz que el italiano "dieci".',
            srsFront: '¿Cómo se dice "diez" en portugués?', srsBack: 'Dez',
            reverseFront: 'Dez', reverseBack: 'Diez',
          },
          {
            id: 'ex5', type: 'translate',
            prompt: 'Traduce al portugués: "cinco"',
            answer: 'cinco',
            explanation: '"Cinco" — idéntico al español, el cognado más directo de este bloque de números.',
            srsFront: '¿Cómo se dice "cinco" en portugués?', srsBack: 'Cinco',
            reverseFront: 'Cinco', reverseBack: 'Cinco',
          },
        ],
      },
      {
        id: 'pt_a1_u4_falar',
        cefr: 'A1',
        descriptor: 'Pode dizer que línguas fala usando o padrão regular dos verbos em -ar.',
        title: 'Que línguas você fala?',
        titleEs: '¿Qué idiomas hablas?',
        dialogue: [
          { speaker: 'João', line: 'Você fala português?' },
          { speaker: 'Maria', line: 'Sim, falo português e espanhol. Você fala inglês?' },
          { speaker: 'João', line: 'Sim, falo inglês e um pouco de português.' },
          { speaker: 'Maria', line: 'Legal!' },
        ],
        phonetics: {
          'você fala português?': 'vo-SE FA-la por-tu-GES?',
          'sim, falo português e espanhol. você fala inglês?': 'sin, FA-lu por-tu-GES i is-pa-NYOL. vo-SE FA-la in-GLES?',
          'sim, falo inglês e um pouco de português.': 'sin, FA-lu in-GLES i un PO-ku dji por-tu-GES.',
          'legal!': 'le-GAU!',
          'um pouco de': 'un PO-ku dji',
          'falo': 'FA-lu', 'fala': 'FA-la', 'falamos': 'fa-LA-mus', 'falam': 'FA-lãun',
          'falar': 'fa-LAR',
        },
        glossary: [
          { target: 'um pouco de', es: 'un poco de', note: null },
          { target: 'Legal!', es: '¡Genial! / ¡Bien!', note: 'Muy usado en el portugués brasileño coloquial para aprobar algo.' },
        ],
        grammar: {
          title: 'Verbos regulares en -ar (ej. "falar" = hablar)',
          explanation: 'A diferencia de ser y ter (irregulares, Unidades 1 y 2 — hay que memorizar cada forma), "falar" sigue un patrón regular que se repite en cientos de verbos portugueses (morar=vivir, estudar=estudiar, escutar=escuchar...). Aprender esta terminación una sola vez multiplica el vocabulario que ya podés conjugar — mismo patrón que "parlare" en italiano, y muy cercano al español (hablo/hablas/habla → falo/fala/fala).',
          table: [
            ['eu', 'falo'], ['você', 'fala'], ['ele/ela', 'fala'],
            ['nós', 'falamos'], ['vocês', 'falam'], ['eles/elas', 'falam'],
          ],
        },
        exercises: [
          {
            id: 'ex1', type: 'fill',
            prompt: 'Completa: Eu ___ português.',
            answer: 'falo',
            explanation: '"eu" + verbos en -ar → terminan en "-o" (falo), igual que en español "hablo".',
            srsFront: 'Eu ___ português. (falar, eu)', srsBack: 'falo',
          },
          {
            id: 'ex2', type: 'fill',
            prompt: 'Completa: Você ___ inglês?',
            answer: 'fala',
            explanation: '"você"/"ele"/"ela" + verbos en -ar → terminan en "-a" (fala).',
            srsFront: 'Você ___ inglês? (falar, você)', srsBack: 'fala',
          },
          {
            id: 'ex3', type: 'fill',
            prompt: 'Completa: Nós ___ espanhol.',
            answer: 'falamos',
            explanation: '"nós" + verbos en -ar → terminan en "-amos" (falamos) — casi idéntico al español "hablamos".',
            srsFront: 'Nós ___ espanhol. (falar, nós)', srsBack: 'falamos',
          },
          {
            id: 'ex4', type: 'translate',
            prompt: 'Traduce al portugués: "hablar" (infinitivo)',
            answer: 'falar',
            explanation: '"Falar" — cognado reconocible; el patrón -ar es el más común entre los verbos portugueses, igual que -are en italiano.',
            srsFront: '¿Cómo se dice "hablar" en portugués?', srsBack: 'Falar',
            reverseFront: 'Falar', reverseBack: 'Hablar',
          },
          {
            id: 'ex5', type: 'translate',
            prompt: 'Traduce al portugués: "¿Hablas portugués?"',
            answer: 'você fala português',
            explanation: '"Você fala português?" — "você" siempre con "fala".',
            srsFront: '¿Cómo se dice "¿Hablas portugués?" en portugués?', srsBack: 'Você fala português?',
            reverseFront: 'Você fala português?', reverseBack: '¿Hablas portugués?',
          },
        ],
      },
      {
        id: 'pt_a1_u5_comer',
        cefr: 'A1',
        descriptor: 'Pode pedir comida usando o segundo padrão de conjugação regular (-er).',
        title: 'O que você quer comer?',
        titleEs: '¿Qué quieres comer?',
        dialogue: [
          { speaker: 'João', line: 'O que você quer comer?' },
          { speaker: 'Maria', line: 'Como um sanduíche. E você?' },
          { speaker: 'João', line: 'Eu como uma pizza.' },
          { speaker: 'Maria', line: 'Que bom!' },
        ],
        phonetics: {
          'o que você quer comer?': 'u ki vo-SE KER ko-MER?',
          'como um sanduíche. e você?': 'KO-mu un san-DUI-chi. i vo-SE?',
          'eu como uma pizza.': 'eu KO-mu U-ma PI-tsa.',
          'que bom!': 'ki BON!',
          'como': 'KO-mu', 'come': 'KO-mi', 'comemos': 'ko-ME-mus', 'comem': 'KO-mãin',
          'comer': 'ko-MER',
        },
        glossary: [
          { target: 'O que você quer comer?', es: '¿Qué quieres comer?', note: null },
          { target: 'Que bom!', es: '¡Qué bueno!', note: 'Expresión de aprobación muy frecuente, cognado directo con el español.' },
        ],
        grammar: {
          title: 'Verbos regulares en -er (ej. "comer" = comer)',
          explanation: 'Segundo patrón regular, después de -ar (Unidad 4, "falar"). Comparten "eu" (-o), pero difieren en el resto: você/ele/ela termina en "-e" (no "-a"), nós en "-emos" (no "-amos"), vocês/eles/elas en "-em" (no "-am"). Reconocer estos dos patrones (-ar, -er) ya cubre gran parte de los verbos regulares portugueses — mismo esquema que -are/-ere en italiano.',
          table: [
            ['eu', 'como'], ['você', 'come'], ['ele/ela', 'come'],
            ['nós', 'comemos'], ['vocês', 'comem'], ['eles/elas', 'comem'],
          ],
        },
        exercises: [
          {
            id: 'ex1', type: 'fill',
            prompt: 'Completa: Eu ___ uma pizza.',
            answer: 'como',
            explanation: '"eu" + verbos en -er → también termina en "-o" (igual que en -ar).',
            srsFront: 'Eu ___ uma pizza. (comer, eu)', srsBack: 'como',
          },
          {
            id: 'ex2', type: 'fill',
            prompt: 'Completa: Você ___ um sanduíche?',
            answer: 'come',
            explanation: '"você"/"ele"/"ela" + verbos en -er → terminan en "-e" (a diferencia de "-a" en -ar).',
            srsFront: 'Você ___ um sanduíche? (comer, você)', srsBack: 'come',
          },
          {
            id: 'ex3', type: 'fill',
            prompt: 'Completa: Nós ___ pizza.',
            answer: 'comemos',
            explanation: '"nós" + verbos en -er → terminan en "-emos" (a diferencia de "-amos" en -ar).',
            srsFront: 'Nós ___ pizza. (comer, nós)', srsBack: 'comemos',
          },
          {
            id: 'ex4', type: 'translate',
            prompt: 'Traduce al portugués: "comer" (infinitivo)',
            answer: 'comer',
            explanation: '"Comer" — idéntico al español; el patrón -er es el segundo más común entre los verbos portugueses.',
            srsFront: '¿Cómo se dice "comer" en portugués?', srsBack: 'Comer',
            reverseFront: 'Comer', reverseBack: 'Comer',
          },
          {
            id: 'ex5', type: 'translate',
            prompt: 'Traduce al portugués: "¿Qué quieres comer?"',
            answer: 'o que você quer comer',
            explanation: '"O que você quer comer?" — expresión fija para pedir comida.',
            srsFront: '¿Cómo se dice "¿Qué quieres comer?" en portugués?', srsBack: 'O que você quer comer?',
            reverseFront: 'O que você quer comer?', reverseBack: '¿Qué quieres comer?',
          },
        ],
      },
      {
        id: 'pt_a1_u6_assistir',
        cefr: 'A1',
        descriptor: 'Pode falar de hábitos simples usando o terceiro padrão de conjugação regular (-ir).',
        title: 'O que você assiste à noite?',
        titleEs: '¿Qué ves de noche?',
        dialogue: [
          { speaker: 'João', line: 'O que você assiste à noite?' },
          { speaker: 'Maria', line: 'Assisto séries. E você?' },
          { speaker: 'João', line: 'Eu assisto filmes.' },
          { speaker: 'Maria', line: 'Que legal!' },
        ],
        phonetics: {
          'o que você assiste à noite?': 'u ki vo-SE a-SIS-tchi a NOI-tchi?',
          'assisto séries. e você?': 'a-SIS-tu SE-riz. i vo-SE?',
          'eu assisto filmes.': 'eu a-SIS-tu FIU-mis.',
          'que legal!': 'ki le-GAU!',
          'à noite': 'a NOI-tchi',
          'assisto': 'a-SIS-tu', 'assiste': 'a-SIS-tchi', 'assistimos': 'a-sis-TCHI-mus', 'assistem': 'a-SIS-tãin',
          'assistir': 'a-sis-TCHIR',
        },
        glossary: [
          { target: 'à noite', es: 'de noche / por la noche', note: null },
          { target: 'séries', es: 'series', note: 'Cognado directo.' },
        ],
        grammar: {
          title: 'Verbos regulares en -ir (ej. "assistir" = ver/mirar)',
          explanation: 'Tercer y último patrón regular, después de -ar (falar, Unidad 4) y -er (comer, Unidad 5). Comparte "eu" (-o) con los otros dos, pero difiere en el resto: você/ele/ela → "-e" (como -er), nós → "-imos" (a diferencia de "-amos"/"-emos"), vocês/eles/elas → "-em" (como -er). Con estos 3 patrones (-ar/-er/-ir) ya podés conjugar la mayoría de los verbos regulares del portugués — mismo esquema que -are/-ere/-ire en italiano.',
          table: [
            ['eu', 'assisto'], ['você', 'assiste'], ['ele/ela', 'assiste'],
            ['nós', 'assistimos'], ['vocês', 'assistem'], ['eles/elas', 'assistem'],
          ],
        },
        exercises: [
          {
            id: 'ex1', type: 'fill',
            prompt: 'Completa: Eu ___ séries.',
            answer: 'assisto',
            explanation: '"eu" + verbos en -ir → también termina en "-o" (igual que -ar y -er).',
            srsFront: 'Eu ___ séries. (assistir, eu)', srsBack: 'assisto',
          },
          {
            id: 'ex2', type: 'fill',
            prompt: 'Completa: Você ___ filmes?',
            answer: 'assiste',
            explanation: '"você"/"ele"/"ela" + verbos en -ir → terminan en "-e" (igual que -er).',
            srsFront: 'Você ___ filmes? (assistir, você)', srsBack: 'assiste',
          },
          {
            id: 'ex3', type: 'fill',
            prompt: 'Completa: Nós ___ séries.',
            answer: 'assistimos',
            explanation: '"nós" + verbos en -ir → terminan en "-imos" (a diferencia de "-amos"/"-emos").',
            srsFront: 'Nós ___ séries. (assistir, nós)', srsBack: 'assistimos',
          },
          {
            id: 'ex4', type: 'translate',
            prompt: 'Traduce al portugués: "ver/mirar" (infinitivo, ej. una serie)',
            answer: 'assistir',
            explanation: '"Assistir" — cognado con "asistir" en español, aunque en portugués su uso principal es "ver/mirar" (TV, películas), no "estar presente en un lugar".',
            srsFront: '¿Cómo se dice "ver/mirar" (una serie) en portugués?', srsBack: 'Assistir',
            reverseFront: 'Assistir', reverseBack: 'Ver/mirar',
          },
          {
            id: 'ex5', type: 'translate',
            prompt: 'Traduce al portugués: "¿Qué ves de noche?"',
            answer: 'o que você assiste à noite',
            explanation: '"O que você assiste à noite?" — "à noite" para expresar "de noche".',
            srsFront: '¿Cómo se dice "¿Qué ves de noche?" en portugués?', srsBack: 'O que você assiste à noite?',
            reverseFront: 'O que você assiste à noite?', reverseBack: '¿Qué ves de noche?',
          },
        ],
      },
      {
        id: 'pt_a1_u7_negacao',
        cefr: 'A1',
        descriptor: 'Pode negar frases simples usando "não" antes do verbo.',
        title: 'Não, obrigada!',
        titleEs: '¡No, gracias!',
        dialogue: [
          { speaker: 'João', line: 'Você assiste novela?' },
          { speaker: 'Maria', line: 'Não, não assisto novela. Prefiro séries.' },
          { speaker: 'João', line: 'Você não fala francês?' },
          { speaker: 'Maria', line: 'Não, não falo francês. Só português e espanhol.' },
        ],
        phonetics: {
          'você assiste novela?': 'vo-SE a-SIS-tchi no-VE-la?',
          'não, não assisto novela. prefiro séries.': 'NÃUN, NÃUN a-SIS-tu no-VE-la. pre-FI-ru SE-riz.',
          'você não fala francês?': 'vo-SE NÃUN FA-la fran-SES?',
          'não, não falo francês. só português e espanhol.': 'NÃUN, NÃUN FA-lu fran-SES. SO por-tu-GES i is-pa-NYOL.',
          'não': 'NÃUN', 'novela': 'no-VE-la', 'prefiro': 'pre-FI-ru', 'só': 'SO',
        },
        glossary: [
          { target: 'novela', es: 'telenovela', note: 'Cognado; formato de ficción muy popular en Brasil.' },
          { target: 'Prefiro', es: 'Prefiero', note: null },
          { target: 'só', es: 'solo/solamente', note: null },
        ],
        grammar: {
          title: 'La negación con "não"',
          explanation: 'Para negar una frase, "não" va antes del verbo — igual que el "no" del español ("no hablo" → "não falo") y el "non" del italiano. A diferencia del español, cuando el portugués responde negando una pregunta suele repetir "não" dos veces: "Você fala francês? Não, não falo." — el primer "não" es la respuesta corta ("no"), el segundo niega el verbo ("no hablo"). No es doble negación como en inglés; es solo la estructura habitual de una respuesta negativa completa.',
          table: [
            ['Eu falo francês.', 'Eu não falo francês.'],
            ['Você tem irmãos?', 'Não, não tenho irmãos.'],
            ['Ele assiste séries.', 'Ele não assiste séries.'],
          ],
        },
        exercises: [
          {
            id: 'ex1', type: 'fill',
            prompt: 'Completa: Eu ___ falo francês.',
            answer: 'não',
            explanation: '"não" va antes del verbo para negar, igual que "no" en español.',
            srsFront: 'Eu ___ falo francês. (negação)', srsBack: 'não',
          },
          {
            id: 'ex2', type: 'fill',
            prompt: 'Completa: Ela ___ come carne.',
            answer: 'não',
            explanation: '"não" antes del verbo, sin importar la persona.',
            srsFront: 'Ela ___ come carne. (negação)', srsBack: 'não',
          },
          {
            id: 'ex3', type: 'translate',
            prompt: 'Traduce al portugués: "No, no hablo francés."',
            answer: 'não, não falo francês',
            explanation: 'Doble "não": el primero responde "no", el segundo niega el verbo "falo".',
            srsFront: '¿Cómo se dice "No, no hablo francés." en portugués?', srsBack: 'Não, não falo francês.',
            reverseFront: 'Não, não falo francês.', reverseBack: 'No, no hablo francés.',
          },
          {
            id: 'ex4', type: 'translate',
            prompt: 'Traduce al portugués: "No tengo hermanos."',
            answer: 'não tenho irmãos',
            explanation: '"Não tenho irmãos" — "não" antes de "tenho" (ter, Unidad 2).',
            srsFront: '¿Cómo se dice "No tengo hermanos." en portugués?', srsBack: 'Não tenho irmãos.',
            reverseFront: 'Não tenho irmãos.', reverseBack: 'No tengo hermanos.',
          },
          {
            id: 'ex5', type: 'translate',
            prompt: 'Traduce al portugués: "solo/solamente"',
            answer: 'só',
            explanation: '"Só" — forma corta y muy usada de "somente".',
            srsFront: '¿Cómo se dice "solo/solamente" en portugués?', srsBack: 'Só',
            reverseFront: 'Só', reverseBack: 'Solo/solamente',
          },
        ],
      },
      {
        id: 'pt_a1_u8_numeros2',
        cefr: 'A1',
        descriptor: 'Pode usar os números de 11 a 20 para falar da idade de outras pessoas.',
        title: 'Quantos anos ele tem?',
        titleEs: '¿Cuántos años tiene él?',
        dialogue: [
          { speaker: 'João', line: 'Quantos anos sua irmã tem?' },
          { speaker: 'Maria', line: 'Ela tem quinze anos. E o seu irmão?' },
          { speaker: 'João', line: 'Ele tem dezoito anos.' },
          { speaker: 'Maria', line: 'Uau, ele já é adulto!' },
        ],
        phonetics: {
          'quantos anos sua irmã tem?': 'KUAN-tus A-nus SU-a ir-MÃ ten?',
          'ela tem quinze anos. e o seu irmão?': 'E-la ten KIN-zi A-nus. i u seu ir-MÃUN?',
          'ele tem dezoito anos.': 'E-li ten de-ZOI-tu A-nus.',
          'uau, ele já é adulto!': 'U-au, E-li ZHA E a-DUL-tu!',
          'uau!': 'U-au!', 'adulto': 'a-DUL-tu',
          'onze': 'ON-zi', 'doze': 'DO-zi', 'treze': 'TRE-zi', 'quatorze': 'kua-TOR-zi',
          'quinze': 'KIN-zi', 'dezesseis': 'de-ze-SEIS', 'dezessete': 'de-ze-SE-tchi',
          'dezoito': 'de-ZOI-tu', 'dezenove': 'de-ze-NO-vi', 'vinte': 'VIN-tchi',
        },
        glossary: [
          { target: 'Uau!', es: '¡Guau!', note: 'Interjección de sorpresa, casi idéntica a la del español.' },
          { target: 'adulto', es: 'adulto', note: 'Cognado directo.' },
        ],
        grammar: {
          title: 'Los números 11-20',
          explanation: 'Repaso de "ter ... anos" (Unidad 3) ahora con números más altos. A diferencia del español, donde 16-19 son una sola palabra fusionada ("dieciséis"), el portugués los arma con "dez" + "e" + la unidad: dezesseis (dez+e+seis), dezessete, dezoito, dezenove — mismo patrón de construcción que el italiano (sedici, diciassette...), solo con otra partícula de unión. 11-15 (onze...quinze) no siguen ningún patrón — hay que memorizarlos igual que en español.',
          table: [
            ['11', 'onze'], ['12', 'doze'], ['13', 'treze'], ['14', 'quatorze'], ['15', 'quinze'],
            ['16', 'dezesseis'], ['17', 'dezessete'], ['18', 'dezoito'], ['19', 'dezenove'], ['20', 'vinte'],
          ],
        },
        exercises: [
          {
            id: 'ex1', type: 'fill',
            prompt: 'Completa: Ela ___ quinze anos.',
            answer: 'tem',
            explanation: 'Repaso de "ter" (Unidades 2 y 3): "ela" va con "tem", también con números más altos.',
            srsFront: 'Ela ___ quinze anos. (ter, ela)', srsBack: 'tem',
          },
          {
            id: 'ex2', type: 'translate',
            prompt: 'Traduce al portugués: "dieciocho"',
            answer: 'dezoito',
            explanation: '"Dezoito" — literalmente "dez" (diez) + "oito" (ocho).',
            srsFront: '¿Cómo se dice "dieciocho" en portugués?', srsBack: 'Dezoito',
            reverseFront: 'Dezoito', reverseBack: 'Dieciocho',
          },
          {
            id: 'ex3', type: 'translate',
            prompt: 'Traduce al portugués: "veinte"',
            answer: 'vinte',
            explanation: '"Vinte" — cognado reconocible del latín viginti.',
            srsFront: '¿Cómo se dice "veinte" en portugués?', srsBack: 'Vinte',
            reverseFront: 'Vinte', reverseBack: 'Veinte',
          },
          {
            id: 'ex4', type: 'translate',
            prompt: 'Traduce al portugués: "trece"',
            answer: 'treze',
            explanation: '"Treze" — no sigue el patrón "dez+e+unidade" de 16-19, hay que memorizarlo suelto, igual que en español.',
            srsFront: '¿Cómo se dice "trece" en portugués?', srsBack: 'Treze',
            reverseFront: 'Treze', reverseBack: 'Trece',
          },
          {
            id: 'ex5', type: 'translate',
            prompt: 'Traduce al portugués: "¿Cuántos años tiene tu hermana?"',
            answer: 'quantos anos sua irmã tem',
            explanation: '"Quantos anos sua irmã tem?" — mismo patrón de la Unidad 3, ahora en 3ª persona.',
            srsFront: '¿Cómo se dice "¿Cuántos años tiene tu hermana?" en portugués?', srsBack: 'Quantos anos sua irmã tem?',
            reverseFront: 'Quantos anos sua irmã tem?', reverseBack: '¿Cuántos años tiene tu hermana?',
          },
        ],
      },
      {
        id: 'pt_a1_u9_lugares',
        cefr: 'A1',
        descriptor: 'Pode perguntar e entender onde fica um lugar usando preposições básicas.',
        title: 'Onde fica o banco?',
        titleEs: '¿Dónde está el banco?',
        dialogue: [
          { speaker: 'João', line: 'Onde fica o banco?' },
          { speaker: 'Maria', line: 'Fica perto daqui, ao lado do mercado.' },
          { speaker: 'João', line: 'E a farmácia?' },
          { speaker: 'Maria', line: 'Fica longe, perto da escola.' },
        ],
        phonetics: {
          'onde fica o banco?': 'ON-dji FI-ka u BAN-ku?',
          'fica perto daqui, ao lado do mercado.': 'FI-ka PER-tu da-KI, au LA-du du mer-KA-du.',
          'e a farmácia?': 'i a far-MA-sia?',
          'fica longe, perto da escola.': 'FI-ka LON-zhi, PER-tu da is-KO-la.',
          'banco': 'BAN-ku', 'mercado': 'mer-KA-du', 'farmácia': 'far-MA-sia', 'escola': 'is-KO-la',
          'perto de': 'PER-tu dji', 'longe de': 'LON-zhi dji', 'ao lado de': 'au LA-du dji',
          'fica': 'FI-ka',
        },
        glossary: [
          { target: 'banco', es: 'banco', note: 'Cognado directo.' },
          { target: 'mercado', es: 'mercado', note: 'Cognado directo.' },
          { target: 'farmácia', es: 'farmacia', note: 'Cognado directo.' },
          { target: 'escola', es: 'escuela', note: null },
        ],
        grammar: {
          title: '"Onde fica...?" y preposiciones de lugar',
          explanation: '"Fica" (de "ficar") es la forma más natural de decir dónde está un lugar fijo en portugués cotidiano — donde el español usa "está" para todo, el portugués prefiere "fica" para ubicaciones. "Perto de" (cerca de), "longe de" (lejos de) y "ao lado de" (al lado de) se contraen con el artículo definido que sigue: perto de + o → perto do, perto de + a → perto da — igual idea que "de + el = del" en español, pero el portugués contrae con "o" y "a" también, no solo con "o".',
          table: [
            ['cerca de', 'perto de'], ['lejos de', 'longe de'],
            ['al lado de', 'ao lado de'], ['está (ubicación)', 'fica'],
          ],
        },
        exercises: [
          {
            id: 'ex1', type: 'fill',
            prompt: 'Completa: O banco ___ perto daqui.',
            answer: 'fica',
            explanation: '"Fica" (no "está") es la forma natural de decir dónde queda un lugar.',
            srsFront: 'O banco ___ perto daqui. (ficar, lugar)', srsBack: 'fica',
          },
          {
            id: 'ex2', type: 'fill',
            prompt: 'Completa: A farmácia fica ___ lado do mercado.',
            answer: 'ao',
            explanation: '"A" + "o" se contrae en "ao" — "ao lado de" (al lado de).',
            srsFront: 'A farmácia fica ___ lado do mercado. (contração a+o)', srsBack: 'ao',
          },
          {
            id: 'ex3', type: 'translate',
            prompt: 'Traduce al portugués: "cerca de"',
            answer: 'perto de',
            explanation: '"Perto de" — se contrae con el artículo que sigue (perto do/da).',
            srsFront: '¿Cómo se dice "cerca de" en portugués?', srsBack: 'Perto de',
            reverseFront: 'Perto de', reverseBack: 'Cerca de',
          },
          {
            id: 'ex4', type: 'translate',
            prompt: 'Traduce al portugués: "lejos de"',
            answer: 'longe de',
            explanation: '"Longe de" — opuesto de "perto de".',
            srsFront: '¿Cómo se dice "lejos de" en portugués?', srsBack: 'Longe de',
            reverseFront: 'Longe de', reverseBack: 'Lejos de',
          },
          {
            id: 'ex5', type: 'translate',
            prompt: 'Traduce al portugués: "¿Dónde está el banco?"',
            answer: 'onde fica o banco',
            explanation: '"Onde fica o banco?" — "fica", no "está", para preguntar por la ubicación de un lugar.',
            srsFront: '¿Cómo se dice "¿Dónde está el banco?" en portugués?', srsBack: 'Onde fica o banco?',
            reverseFront: 'Onde fica o banco?', reverseBack: '¿Dónde está el banco?',
          },
        ],
      },
      {
        id: 'pt_a1_u10_cores',
        cefr: 'A1',
        descriptor: 'Pode descrever a cor de objetos simples usando a concordância de gênero dos adjetivos.',
        title: 'De que cor é?',
        titleEs: '¿De qué color es?',
        dialogue: [
          { speaker: 'João', line: 'De que cor é sua casa?' },
          { speaker: 'Maria', line: 'Minha casa é branca. E o seu carro?' },
          { speaker: 'João', line: 'Meu carro é vermelho.' },
          { speaker: 'Maria', line: 'Que bonito!' },
        ],
        phonetics: {
          'de que cor é sua casa?': 'dji ki KOR E SU-a KA-za?',
          'minha casa é branca. e o seu carro?': 'MI-nya KA-za E BRAN-ka. i u seu KA-hu?',
          'meu carro é vermelho.': 'meu KA-hu E ver-ME-lyu.',
          'que bonito!': 'ki bo-NI-tu!',
          'cor': 'KOR', 'casa': 'KA-za', 'carro': 'KA-hu', 'bonito': 'bo-NI-tu',
          'branco': 'BRAN-ku', 'branca': 'BRAN-ka',
          'vermelho': 'ver-ME-lyu', 'vermelha': 'ver-ME-lya',
          'preto': 'PRE-tu', 'preta': 'PRE-ta',
          'amarelo': 'a-ma-RE-lu', 'amarela': 'a-ma-RE-la',
          'verde': 'VER-dji', 'azul': 'a-ZUU',
        },
        glossary: [
          { target: 'casa', es: 'casa', note: 'Cognado directo.' },
          { target: 'carro', es: 'auto/carro', note: null },
          { target: 'bonito', es: 'bonito/lindo', note: null },
        ],
        grammar: {
          title: 'Los colores y la concordancia de género de los adjetivos',
          explanation: 'Muchos adjetivos de color en portugués cambian de terminación según el género del sustantivo, igual que en español (blanco/blanca): branco/branca, vermelho/vermelha, preto/preta, amarelo/amarela — terminan en "-o" para masculino y cambian a "-a" para femenino. Otros son invariables (no cambian con el género), también igual que en español: verde, azul. Nota: para el color negro, el portugués brasileño cotidiano usa "preto" (no "negro", que existe pero se asocia más a raza/identidad que al color de un objeto).',
          table: [
            ['blanco/blanca', 'branco/branca'], ['rojo/roja', 'vermelho/vermelha'],
            ['negro/negra', 'preto/preta'], ['amarillo/amarilla', 'amarelo/amarela'],
            ['verde', 'verde'], ['azul', 'azul'],
          ],
        },
        exercises: [
          {
            id: 'ex1', type: 'fill',
            prompt: 'Completa: Minha casa é ___. (blanca)',
            answer: 'branca',
            explanation: '"Casa" es femenino → el adjetivo termina en "-a" (branca), igual que en español.',
            srsFront: 'Minha casa é ___. (branco/a, femenino)', srsBack: 'branca',
          },
          {
            id: 'ex2', type: 'fill',
            prompt: 'Completa: Meu carro é ___. (rojo)',
            answer: 'vermelho',
            explanation: '"Carro" es masculino → el adjetivo termina en "-o" (vermelho).',
            srsFront: 'Meu carro é ___. (vermelho/a, masculino)', srsBack: 'vermelho',
          },
          {
            id: 'ex3', type: 'translate',
            prompt: 'Traduce al portugués: "verde"',
            answer: 'verde',
            explanation: '"Verde" — idéntico al español, y no cambia con el género (invariable).',
            srsFront: '¿Cómo se dice "verde" en portugués?', srsBack: 'Verde',
            reverseFront: 'Verde', reverseBack: 'Verde',
          },
          {
            id: 'ex4', type: 'translate',
            prompt: 'Traduce al portugués: "negro" (color, masculino)',
            answer: 'preto',
            explanation: '"Preto" — la palabra de uso cotidiano para el color negro en un objeto (no "negro").',
            srsFront: '¿Cómo se dice "negro" (color) en portugués?', srsBack: 'Preto',
            reverseFront: 'Preto', reverseBack: 'Negro (color)',
          },
          {
            id: 'ex5', type: 'translate',
            prompt: 'Traduce al portugués: "¿De qué color es tu carro?"',
            answer: 'de que cor é o seu carro',
            explanation: '"De que cor é o seu carro?" — misma estructura que en español.',
            srsFront: '¿Cómo se dice "¿De qué color es tu carro?" en portugués?', srsBack: 'De que cor é o seu carro?',
            reverseFront: 'De que cor é o seu carro?', reverseBack: '¿De qué color es tu carro?',
          },
        ],
      },
    ],
  },
};

function normalizeAnswer(s) {
  return s
    .toLowerCase()
    .normalize('NFD').replace(/[̀-ͯ]/g, '') // quita acentos
    .replace(/[¿?¡!.,]/g, '')
    .trim();
}
